server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: cualquier ruta que no sea archivo real cae a index.html (Vue Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
